version = 0.1

[default.build.parameters]
region = "us-east-1"

[prod.deploy.parameters]
stack_name = "Streaming-Api-Prod"
resolve_s3 = true
s3_prefix = "Streaming-Api-Prod"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
